from django.shortcuts import render


def index_1(request):
    context = {
        "data": [
            {
                "tors_num": "1",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "2",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "3",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "4",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "5",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "6",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            }, {
                "tors_num": "7",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "8",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "9",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            }, {
                "tors_num": "10",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "11",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "12",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            }, {
                "tors_num": "13",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "14",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "15",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            }, {
                "tors_num": "16",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "17",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "18",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            }, {
                "tors_num": "19",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "20",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "21",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            }, {
                "tors_num": "22",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "23",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "24",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            }, {
                "tors_num": "25",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "26",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },

        ]
    }
    return render(request, 'dashboard/index_1.html', context)


def index_2(request):
    return render(request, 'dashboard/index_2.html')


def index_3(request):
    return render(request, 'dashboard/index_3.html')


def index_4(request):
    context = {
        "data": [
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum doloerdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non tempor lorem. Sed commodo et tortor et lacinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "starter",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur  dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consecplacerat malesu, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "standard",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur alor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipiscing cinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "premium",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit ame dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adr lorem. Sed commodo et tortor et lacinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "starter",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum doloerdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non tempor lorem. Sed commodo et tortor et lacinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "starter",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur  dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consecplacerat malesu, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "standard",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur alor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipiscing cinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "premium",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit ame dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adr lorem. Sed commodo et tortor et lacinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "starter",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },
            {
                "trainer_id": "1",
                "trainer_name": "Henry Doe",
                "trainer_info": "Lorem ipsum dolor sit amet, consectetur adip nisi, imperdiet ac dolor ac, facilisis tempus risus. Maecenas eget purus id mauris imperdiet viverra. Suspendisse at molestie dui, a tempus felis. ",
                "trainer_biodate": "Lorem ipsum dolor sit amet, consectetur adipinia. Nullam placerat malesuada ligula. Curabitur mauris nisi, imperdiet ac dolor ac, facilisis tempus ",
                "trainer_level": "elite",
            },


        ]
    }
    return render(request, "dashboard/index_4.html", context)


def index_5(request):
    return render(request, "dashboard/index_5.html")


def index_6(request):
    return render(request, "dashboard/index_6.html")


def add_event(request):
    return render(request, "dashboard/add_event.html")


def profile(request):
    context = {
        "data": [
            {
                "tors_num": "1",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "2",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "3",
                "creation_date": "03.03.2022",
                "presentation": "03.03.2022",
                "created_by": "David Hammer",
                "budget_center": "Budget center one ",
                "Institution_name": "OpenAI",
                "subject": "Robotic",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
            {
                "tors_num": "4",
                "creation_date": "01.01.2022",
                "presentation": "02.01.2022",
                "created_by": "Thomas Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "AI",
                "tors_status": "In progress",
                "payment_status": "No",
            },
            {
                "tors_num": "5",
                "creation_date": "02.02.2022",
                "presentation": "02.02.2022",
                "created_by": "Jane Doe",
                "budget_center": "Budget center one ",
                "Institution_name": "MIT",
                "subject": "Iot",
                "tors_status": "In progress",
                "payment_status": "yes",
            },
        ]
    }
    return render(request, "dashboard/profile.html", context)
